# Generated by Django 6.0.7 on 2026-08-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_usermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
